set_property SRC_FILE_INFO {cfile:D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/constrs_1/imports/fpga/main.xdc rfile:../../../fpga.srcs/constrs_1/imports/fpga/main.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports CLK_N]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18 [get_ports CLK_P]
