# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Projects/computer_structure/ridecore/fpga/fpga.cache/wt [current_project]
set_property parent.project_path D:/Projects/computer_structure/ridecore/fpga/fpga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Projects/computer_structure/ridecore/fpga/fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/constants.vh
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/alu_ops.vh
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/rv32_opcodes.vh
}
read_verilog -library xil_defaultlib {
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/dualport_ram.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/ram_sync.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/btb.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/ram_sync_nolatch.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/src_manager.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/gshare.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/alu.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/multiplier.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/srcsel.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/search_be.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/decoder.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/rs_mul.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/rs_ldst.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/rs_reqgen.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/rrf_freelistmanager.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/oldest_finder.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/storebuf.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/reorderbuf.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/mpft.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/exunit_branch.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/tag_generator.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/imm_gen.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/pipeline_if.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/brimm_gen.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/exunit_mul.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/rs_branch.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/rs_alu.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/srcopr_manager.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/arf.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/prioenc.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/rrf.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/exunit_alu.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/exunit_ldst.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/alloc_issue_ino.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/imem.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/define.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/uart.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/pipeline.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/system.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/dmem.v
  D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/sources_1/imports/fpga/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/constrs_1/imports/fpga/main.xdc
set_property used_in_implementation false [get_files D:/Projects/computer_structure/ridecore/fpga/fpga.srcs/constrs_1/imports/fpga/main.xdc]


synth_design -top top -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
