# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/luzhe/Desktop/camera_zybo_01_01/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/luzhe/Desktop/camera_zybo_01_01/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/luzhe/Desktop/camera_zybo_01_01/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/luzhe/Desktop/pipeline_withoutcache_new/signext.v
  C:/Users/luzhe/Desktop/pipeline_withoutcache_new/regFile.v
  C:/Users/luzhe/Desktop/pipeline_withoutcache_new/memory.v
  C:/Users/luzhe/Desktop/pipeline_withoutcache_new/instructionMem.v
  C:/Users/luzhe/Desktop/pipeline_withoutcache_new/control.v
  C:/Users/luzhe/Desktop/pipeline_withoutcache_new/AluCtr.v
  C:/Users/luzhe/Desktop/pipeline_withoutcache_new/Alu.v
  C:/Users/luzhe/Desktop/pipeline_withoutcache_new/multiMips.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/luzhe/Desktop/camera_zybo_01_01/project_1/mips.xdc
set_property used_in_implementation false [get_files C:/Users/luzhe/Desktop/camera_zybo_01_01/project_1/mips.xdc]


synth_design -top multiMips -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef multiMips.dcp

catch { report_utilization -file multiMips_utilization_synth.rpt -pb multiMips_utilization_synth.pb }
